import { Inter } from "next/font/google";
import "./globals.css";
import DefaultHome from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Delica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultHome/>
        {children}
        
        </body>
    </html>
  );
}
